# Generated by Django 3.1.2 on 2020-11-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRF_profile_image', models.ImageField(default='Noimage.jpg', upload_to='profile_accounts_images/')),
                ('PRF_phone', models.CharField(blank=True, max_length=90, null=True)),
                ('PRF_Location', models.CharField(blank=True, max_length=276, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
