# Generated by Django 3.1.2 on 2020-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PRF_profile_image',
            field=models.ImageField(default='Noimage.jpg', upload_to=''),
        ),
    ]
