# Generated by Django 3.1.2 on 2020-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201107_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PRF_profile_image',
            field=models.ImageField(default='profile_accounts_images/Noimage.jpg', upload_to=''),
        ),
    ]
