# Generated by Django 3.1.2 on 2020-11-03 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_datetime', models.DateField(auto_now=True)),
                ('comment_date_time', models.DateTimeField(auto_now=True)),
                ('comment_content', models.TextField(max_length=700)),
                ('comment_like', models.IntegerField(default=0)),
                ('comment_auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DB_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now=True)),
                ('comment_content', models.CharField(max_length=1000)),
                ('comment_likes', models.IntegerField(default=0)),
                ('Comment_Count_X_finall', models.CharField(blank=True, max_length=100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, null=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenting', to='bloger.comment')),
            ],
        ),
        migrations.CreateModel(
            name='DB_Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=200)),
                ('date_time', models.DateField(auto_now=True)),
                ('content', models.TextField(max_length=4000)),
                ('images', models.ImageField(upload_to='BLOGER/')),
                ('Keyworda', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.anm_category')),
                ('tags', models.ManyToManyField(to='bloger.DB_Tags')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_self_Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloger.db_bloger'),
        ),
    ]
