# Generated by Django 3.1.2 on 2020-11-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0002_replaytocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaytocomment',
            name='comment_content',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
