# Generated by Django 3.1.2 on 2020-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0003_replaytocomment_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaytocomment',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
