# Generated by Django 3.1.2 on 2020-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0004_replaytocomment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaytocomment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
