# Generated by Django 3.1.2 on 2020-11-01 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0005_replaytocomment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaytocomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenting', to='bloger.comment'),
        ),
    ]
