# Generated by Django 3.1.2 on 2020-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0006_auto_20201101_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaytocomment',
            name='slug',
        ),
        migrations.AddField(
            model_name='replaytocomment',
            name='comment_likes',
            field=models.IntegerField(default=0),
        ),
    ]
