# Generated by Django 3.1.2 on 2020-11-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ANM_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=90)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ANM_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANM_Genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ANM_Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANM_Quality', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ANM_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANM_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ANM_Studios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANM_Studios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ANM_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANM_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANM_title', models.CharField(max_length=290)),
                ('ANM_sub_title', models.CharField(max_length=100)),
                ('ANM_description', models.TextField(max_length=490)),
                ('ANM_image', models.ImageField(upload_to='ANM_IMAGES/')),
                ('ANM_Date_aired', models.DateTimeField()),
                ('ANM_Scores', models.CharField(max_length=70)),
                ('ANM_Rating', models.CharField(max_length=70)),
                ('ANM_Duration', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('ANM_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.anm_category')),
                ('ANM_Quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.anm_quality')),
                ('ANM_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.anm_status')),
                ('ANM_Studios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.anm_studios')),
                ('ANM_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.anm_type')),
                ('Genre', models.ManyToManyField(to='BLOG.ANM_Genre')),
            ],
        ),
        migrations.CreateModel(
            name='comment_self_anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetima', models.TimeField(auto_now=True)),
                ('Comment', models.TextField(max_length=450)),
                ('auther', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('self_animee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.blog')),
            ],
        ),
    ]
