# Generated by Django 3.1.2 on 2020-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_comment_self_anime_prf_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_self_anime',
            name='PRF_profile_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
