# Generated by Django 3.1.2 on 2020-11-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201107_1853'),
        ('BLOG', '0003_auto_20201107_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_self_anime',
            name='PRF_profile_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
