# Generated by Django 3.1.2 on 2020-11-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_auto_20201107_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_self_anime',
            name='PRF_profile_image',
        ),
    ]
