# Generated by Django 3.1.2 on 2020-11-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0009_remove_comment_self_anime_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_self_anime',
            name='datetima',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
